---
# tasks file for jpnewman.artifactory

#- include: platforms/redhat.yml
#  when: ansible_os_family == 'RedHat'

- include: platforms/ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

  #- include: platforms/debian.yml
  #when: ansible_os_family == 'Debian'

- name: Add license file
  tags: ["artifactory_license"]
  copy:
    src: "{{ artifactory_license_file }}"
    dest: "{{ artifactory_license_path }}"
    owner: artifactory
    group: artifactory
    mode: 0644
  when: artifactory_type | lower == 'pro' and artifactory_license_file is defined and artifactory_license_file | default(None) != None
  notify:
    - restart artifactory
    - restart apache

- include: databases/mysql.yml
  when: artifactory_database.type | lower == 'mysql'

# artifactory_jmx_enable
- name: Artifactory JMX Enable
  lineinfile:
    dest: "{{ artifactory_default_file }}"
    insertafter: '^(export\s+JAVA_OPTIONS=\"$JAVA_OPTIONS)|(export\s+JAVA_OPTIONS=\")'
    line: "{{ artifactory_jmx_java_options }}"
    state: present
  when: artifactory_jmx_enable is defined
  notify:
    - restart artifactory
    - restart apache

- name: Create jmxterm Directory
  file:
    path: '/opt/jmxterm/'
    state: directory
    mode: 0755

- name: Download jmxterm
  get_url:
    url: "{{ artifactory_jmx_jmxterm_url }}"
    dest: "/opt/jmxterm/jmxterm.jar"
    mode: 0644
    timeout: 45
  retries: 3
  delay: 10
  when: artifactory_jmx_jmxterm_install is defined and artifactory_jmx_jmxterm_install

# when: artifactory_run_as_service
