---

- name: Add Artifactory Pro RPM
  yum_repository:
    name: artifactory-pro-rpms
    description: Artifactory Pro
    baseurl: https://bintray.com/jfrog/artifactory-pro-rpms/rpm
  when: artifactory_type | lower == 'pro'

- name: Add Artifactory OSS RPM
  yum_repository:
    name: artifactory-rpms
    description: Artifactory OSS
    baseurl: https://bintray.com/jfrog/artifactory-rpms/rpm
  when: artifactory_type | lower == 'oss'

- name: Install Artifactory
  yum:
    name: "jfrog-artifactory-{{ artifactory_type | lower }}"
    state: present
  notify:
    - restart artifactory
    - restart apache
