
---

- name: Add Artifactory apt repo key
  apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=jfrog
    state: present

- name: Add Artifactory Pro apt repo
  apt_repository:
    repo: 'deb https://jfrog.bintray.com/artifactory-pro-debs {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes
    filename: jfrog-artifactory-pro
  when: artifactory_type | lower == 'pro'

- name: Add Artifactory OSS apt repo
  apt_repository:
    repo: 'deb https://jfrog.bintray.com/artifactory-debs {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes
    filename: jfrog-artifactory-oss
  when: artifactory_type | lower == 'oss'

- name: Install Artifactory
  apt:
    name: "jfrog-artifactory-{{ artifactory_type | lower }}"
    state: present
  notify:
    - restart artifactory
    - restart apache

# derby-tools
# Currently only derby-tools 10.10.1.1-1 and not 10.11 is available via debian repositories
- name: Install Derby Tools
  apt:
    name: derby-tools
    state: present
    update_cache: yes
  when: artifactory_database.type | lower == 'derby' and artifactory_derby_tools_install and artifactory_derby_tools_url is not defined

# JDBC
- name: Check if JDBC is already installed
  stat:
    path: "{{ artifactory_home }}/tomcat/lib/{{ artifactory_database_file_title }}-bin.jar"
  register: jdbc_installed
  check_mode: no
  changed_when: False

- name: Download JDBC Connector for MySQL
  get_url:
    url: "{{ artifactory_database_jdbc_url }}"
    dest: /tmp
  retries: 3
  when: artifactory_database_jdbc_url is defined and not jdbc_installed.stat.exists

- name: Extract JDBC Connector for MySQL
  unarchive:
    src: "/tmp/{{ artifactory_database_file_title }}.tar.gz"
    dest: /tmp
    creates: "/tmp/{{ artifactory_database_file_title }}/"
    remote_src: yes
  when: artifactory_database_jdbc_url is defined and not jdbc_installed.stat.exists

- name: Move JDBC Connector for MySQL to Tomcat lib folder
  command: "cp /tmp/{{ artifactory_database_file_title }}/{{ artifactory_database_file_title }}-bin.jar {{ artifactory_home }}/tomcat/lib"
  when: artifactory_database_jdbc_url is defined and not jdbc_installed.stat.exists
  notify:
    - restart artifactory
    - restart apache
